### ISSUE TITLE
Can Enter Any Hall Using Any UID

### ISSUE THREAD

**Issue by aryan-vora23** [aarchie-r/surakshIIT#3]
Given that we have provided the address and room number during registration, there should be a check to ensure that the hall we are currently entering matches the hall of residence of the person we are visiting. However, this is currently not the case as we can enter Hall 1 using a UID of a person residing in Hall 6.

**Comment by uditpd3000** [comment]
This bug has been fixed.
Now we will check if the entered hall and the host's hall match or not.
Only after that the entry will be confirmed , otherwise you will get an error like this

![Screenshot from 2022-04-21 00-14-54](https://user-images.githubusercontent.com/75174340/164301002-95bceb3b-0b35-44c4-bb41-c03a65c8f25d.png)
